apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-mssql
  namespace: api
  labels:
    type: local
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/db-data"