apiVersion: v1
kind: Secret
metadata:
  name: app
  namespace: api
type: Opaque
data:
  # echo -n 9ad1ce15f7255a59f16e34c098dc8fe42381d88cd0bdecb242320644d20b15bc | base64 | pbcopy
  secret: OWFkMWNlMTVmNzI1NWE1OWYxNmUzNGMwOThkYzhmZTQyMzgxZDg4Y2QwYmRlY2IyNDIzMjA2NDRkMjBiMTViYw==
