apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: api
type: Opaque
data:
  # echo -n frPB372dCgDRcTri | base64 | pbcopy
  password: dHJhaW5pbmdfcHc=
  root_password: ZnJQQjM3MmRDZ0RSY1RyaQ==
