apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: api
  labels:
    app: dotnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
        - name: dotnet-app
          image: manhhoangseta/devops-dotnet-app:{tag}
          command: ["dotnet", "DevOpsTrainingDotnet.dll"]
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            exec:
              command:
                - "true"
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 15
